export const actionTypes = {
    AUTH_INIT: 'AUTH_INIT',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',
    AUTH_RESET: 'AUTH_RESET',
    DISMISS_ERROR_MESSAGE: 'DISMISS_ERROR_MESSAGE',
    SAVE_URL: 'SAVE_URL'
}
