export const actionTypes = {
    // Auth
    VALIDATE_TOKEN: 'VALIDATE_TOKEN',
    AUTH_INIT: 'AUTH_INIT',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',
    RESET_AUTH: 'RESET_AUTH',
    CLEAR_AUTH_ERROR: 'CLEAR_AUTH_ERROR',
    SAVE_URL: 'SAVE_URL',
    // Posts
    FETCH_POSTS_INIT: 'FETCH_POSTS_INIT',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    CLEAR_POSTS_ERROR: 'CLEAR_POSTS_ERROR',
    CLEAR_POSTS: 'CLEAR_POSTS'
}
