export const actionTypes = {
    // Auth
    AUTH_INIT: 'AUTH_INIT',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',
    RESET_AUTH: 'RESET_AUTH',
    RESET_AUTH_ERROR: 'RESET_AUTH_ERROR',
    SAVE_URL: 'SAVE_URL',
    // Posts
    FETCH_POSTS_INIT: 'FETCH_POSTS_INIT',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    RESET_POSTS_ERROR: 'RESET_POSTS_ERROR'
}
